In [1]:
%%HTML
<style type="text/css">
    h1{
        color:#FE7E00;
        font-weight:bold;
    }
    h2{
        color:#0D47A1;
        # font-weight:bold;
    }
    h3{
        color:#408080;
    }
    th{
        border:1px solid black !important;
        color:white !important;
        background-color:#FE7E00 !important;
    }
    # th td{
    #     border:1px solid black;
    # }
    tr{
        border:1px solid black !important;
        border-collapse:collapse !important;
    }
    td{
        border:1px solid black !important;
    }
    tr td:hover{
        background-color:blueviolet !important;
        color:white !important;
        transform:scale(1.05)
    }
    .code_{
        background-color:#1c1f2b !important;
        color:#9dbed3 !important; 
        white-sapce:pre-wrap;
    }
</style>

<h1>N维数组-ndarray</h1>
<p class="dsc">所谓ndarry就是n dimission arry,即n维数组</p>
<h2>1学习目标</h2>
<ul>
    <li>说明数组的属性，形状，类型</li>
</ul>

<h2>2数组的属性</h2>

<table>
<thead>
<tr class="tline">
<th style="text-align:center">属性名字</th>
<th style="text-align:center">属性解释</th>
</tr>
</thead>
<tbody>
<tr class="tline">
<td style="text-align:center"><strong>ndarray.shape</strong></td>
<td style="text-align:center">数组维度的元组</td>
</tr>
<tr class="tline">
<td style="text-align:center">ndarray.ndim</td>
<td style="text-align:center">数组维数</td>
</tr>
<tr class="tline">
<td style="text-align:center">ndarray.size</td>
<td style="text-align:center">数组中的元素数量</td>
</tr>
<tr class="tline">
<td style="text-align:center">ndarray.itemsize</td>
<td style="text-align:center">一个数组元素的长度（字节）</td>
</tr>
<tr class="tline">
<td style="text-align:center"><strong>ndarray.dtype</strong></td>
<td style="text-align:center">数组元素的类型</td>
</tr>
</tbody>
</table>

In [ ]:
# 导入numpy模块
import numpy as np

In [ ]:
# 创建数组
score = np.array(
    [[80, 89, 86, 67, 79],
    [78, 97, 89, 67, 81],
    [90, 94, 78, 67, 74],
    [91, 91, 90, 67, 69],
    [76, 87, 75, 67, 86],
    [70, 79, 84, 67, 84],
    [94, 92, 93, 67, 64],
    [86, 85, 83, 67, 80]]
)

In [15]:
score
score.shape #输出数组的形状，第一个代表行数第二个数字代表列数

(8, 5)

In [16]:
score.ndim #输出数组的维数即n dimmision 显示的数字2即为二维数组

2

In [18]:
score.size #显示元素的数量

40

In [19]:
score.itemsize #每个元素的字节大小

8

In [20]:
score.dtype #显示数组的类型

dtype('int64')

<h2>3数组的形状</h2>

<img src="./imgs/数组2.png">

In [34]:
# 创建不同形状的数组
a1 = np.array([1,3,5]) #一维数组
a2 = np.array([[1,2],[4,5]]) #二维数组
a3 = np.array([[[1,2,3],[5,6,7]],[[4,8,9],[2,2,5]]]) #三维数组
# 看有几个中括号就是几维数组

In [35]:
print(a1)
a1.shape #1行3列的一个一维数组

[1 3 5]


(3,)

In [36]:
print(a2)
a2.shape #2行2列两个2维数组组成的一个二维数组,其中每个数组中又有两个元素

[[1 2]
 [4 5]]


(2, 2)

In [37]:
print(a3)
a3.shape #3维数组就是二维数组的叠加 
# 如何理解223？两个二维数组,两个二维数组之中每个数组有两个一维数组,两个一维数组中有三个数据

[[[1 2 3]
  [5 6 7]]

 [[4 8 9]
  [2 2 5]]]


(2, 2, 3)

<h2>4ndarry的类型</h2>

<table>
<thead>
<tr class="tline">
<th style="text-align:center">名称</th>
<th style="text-align:center">描述</th>
<th style="text-align:center">简写</th>
</tr>
</thead>
<tbody>
<tr class="tline">
<td style="text-align:center">np.bool</td>
<td style="text-align:center">用一个字节存储的布尔类型（True或False）</td>
<td style="text-align:center">'b'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.int8</td>
<td style="text-align:center">一个字节大小，-128 至 127</td>
<td style="text-align:center">'i'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.int16</td>
<td style="text-align:center">整数，-32768 至 32767</td>
<td style="text-align:center">'i2'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.int32</td>
<td style="text-align:center">整数，-2^31​ 至 2^32 -1</td>
<td style="text-align:center">'i4'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.int64</td>
<td style="text-align:center">整数，-2^63 至 2^63 - 1</td>
<td style="text-align:center">'i8'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.uint8</td>
<td style="text-align:center">无符号整数，0 至 255</td>
<td style="text-align:center">'u'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.uint16</td>
<td style="text-align:center">无符号整数，0 至 65535</td>
<td style="text-align:center">'u2'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.uint32</td>
<td style="text-align:center">无符号整数，0 至 2^32 - 1</td>
<td style="text-align:center">'u4'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.uint64</td>
<td style="text-align:center">无符号整数，0 至 2^64 - 1</td>
<td style="text-align:center">'u8'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.float16</td>
<td style="text-align:center">半精度浮点数：16位，正负号1位，指数5位，精度10位</td>
<td style="text-align:center">'f2'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.float32</td>
<td style="text-align:center">单精度浮点数：32位，正负号1位，指数8位，精度23位</td>
<td style="text-align:center">'f4'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.float64</td>
<td style="text-align:center">双精度浮点数：64位，正负号1位，指数11位，精度52位</td>
<td style="text-align:center">'f8'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.complex64</td>
<td style="text-align:center">复数，分别用两个32位浮点数表示实部和虚部</td>
<td style="text-align:center">'c8'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.complex128</td>
<td style="text-align:center">复数，分别用两个64位浮点数表示实部和虚部</td>
<td style="text-align:center">'c16'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.object_</td>
<td style="text-align:center">python对象</td>
<td style="text-align:center">'O'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.str_</td>
<td style="text-align:center">字符串</td>
<td style="text-align:center">'S'</td>
</tr>
<tr class="tline">
<td style="text-align:center">np.unicode_</td>
<td style="text-align:center">unicode类型</td>
<td style="text-align:center">'U'</td>
</tr>
</tbody>
</table>

<p>创建数组指定的类型</p>

In [61]:
arr1 = np.array([[1,2,3],[4,5,6]],dtype=np.float32)

In [63]:
arr1.dtype #指定类型成功，确实是我们指定的类型

dtype('float32')

In [70]:
strarr = np.array([['python','java','c'],['javascript','r','jula']],dtype=np.str_)

In [73]:

print(strarr)
strarr.dtype

[['python' 'java' 'c']
 ['javascript' 'r' 'jula']]


dtype('<U10')