In [13]:
%%HTML
<style type="text/css">
    h1{
        color:#FE7E00;
        font-weight:bold;
    }
    h2{
        color:#0D47A1;
        # font-weight:bold;
    }
    h3{
        color:#3c3c3c;
    }
    th{
        border:1px solid black;
        color:white;
        background-color:#FE7E00;
    }
    # th td{
    #     border:1px solid black;
    # }
    .tline{
        border:1px solid black;
        border-collapse:collapse;
    }
    .tline td{
        border:1px solid black;
    }
    .tline td:hover{
        background-color:blueviolet;
        color:white;
        transform:scale(1.05)
    }
</style>

<h1>生成0和1的数组</h1>
<ul>
<li>np.ones(shape,dtype)</li>
<li>np.ones_like(a,dtype)</li>
<li>np.zeros(shape,dtype)</li>
<li>np.zeros_like(shape,dtype)</li>
</ul>

In [2]:
# 导包
import numpy as np

<h2>1.1生成0,1数组</h2>

In [8]:
# 生成0,1数组
arr1 = np.ones([3,4])
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros_like(arr1) #利用zeros_like可以生成形状与arr1一样的全0元素的数组

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<h2>1.2从现在数组中生成</h2>

<h3>生成方式1 np.arry(object,dtype)</h3>

In [8]:
a = np.array([[1,2,3],[4,5,6]])

In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a1 = np.array(a)

In [11]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

<h3>生成方式2 np.asarry()</h3>

In [12]:
a3=np.asarray(a)

In [13]:
a3

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
a[0,0]=100

In [15]:
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [16]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

<p>可以看到，a1只是深拷贝，并没有随着a的变化而变化，即a1用np.arry()生成了属于自己的数据而不是简单使指向a的地址</p>

In [17]:
a3 

array([[100,   2,   3],
       [  4,   5,   6]])

<p>而a3是深拷贝,所以np.asarry()是浅拷贝，随着a的变化而变化</p>

<h2>1.3 生成固定范围的数组</h2>

<h3>1.3.1 np.linspace(start,stop,num,endpoint)</h3>
<ul>
<li>创建等差数组--指定数量</li>
<li>
参数
<ul>
<li>start:序列的起始值</li>
<li>stop: 序列的结束值</li>
<li>num:要生成的等间隔样例数量，默认为50</li>
<li>endpoint:序列中是否包含stop值,默认为true</li>
</ul>
</li>
</ul>

In [21]:
# 生成等间隔的数组
arr_1=np.linspace(0,100,11)

In [22]:
arr_1

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

<h3>1.3.2 np.arange(start,stop,step,dtype)</h3>
<ul>
<li>创建等差数组 - 指定步长</li>
<li>
    参数
<ul>
    <li>step:步长</li>
</ul>
</li>
</ul>

In [18]:
np.arange(10,50,2) #对比python中的列表进行理解

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

<h3>1.3.3 np.logspace(start,stop,num)</h3>
<ul>
<li>创建以10为底的等比数列</li>
<li>参数
<ul>
    <li>num:要生成的等比数列的数量，默认为50</li>
</ul>
</li>
</ul>

In [3]:
# 生成10的n次方
arr_los = np.logspace(0,2,3)
# 0,2,3 从10的0 次方到 10的2次方

In [4]:
arr_los

array([  1.,  10., 100.])

In [5]:
arr_los?

Type:        ndarray
String form: [  1.  10. 100.]
Length:      3
File:        d:\virtualenvs\ai\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, optional
    Any object that

In [11]:
help(np.logspace(0,1))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec