In [78]:
%%HTML
<style type='text/css'>
    *{
        background-color:#E3EDCD;
        # background-color:black;
        # color:white;
        
    }
    h1{
        color:#1976d2;
    }
    h2{
        color:#f57c00;
    }
    h3{
        color:#ba37ff;
    }
    table{
        border:1px solid black !important;
        border-collapse:collapse !important;
    }
    th{
        background-color:blueviolet !important;
        text-align:center;
        color:white;
    }
    th,td{
        border:0.1px solid black !important;
        transition:0.2s all liner;
        
    }
    td:hover{
        transform:scale(1.1);
        background-color:orange;
        color:blueviolet;
    }
</style>

<h1>第二章 numpy入门</h1>

<p>本章和第 3 章将介绍通过 Python 有效导入、存储和操作内存数据的主
要技巧。这个主题非常广泛，因为数据集的来源与格式都十分丰富，比
如文档集合、图像集合、声音片段集合、数值数据集合，等等。这些数
据虽然存在明显的异构性，但是将所有数据简单地看作数字数组非常有
助于我们理解和处理数据。</p>

<p>例如，可以将图像（尤其是数字图像）简单地看作二维数字数组，这些
数字数组代表各区域的像素值；声音片段可以看作时间和强度的一维数
组；文本也可以通过各种方式转换成数值表示，一种可能的转换是用二
进制数表示特定单词或单词对出现的频率。不管数据是何种形式，第一
步都是将这些数据转换成数值数组形式的可分析数据（5.4 节将更详细
地介绍一些实现这种数据转换的示例）。</p>

<p>正因如此，有效地存储和操作数值数组是数据科学中绝对的基础过程。
我们将介绍 Python 中专门用来处理这些数值数组的工具：NumPy 包和
Pandas 包（将在第 3 章介绍）。</p>

<p>本章将详细介绍 NumPy。NumPy（Numerical Python 数字化python的简称）提供了高
效存储和操作密集数据缓存的接口。在某些方面，NumPy 数组与
Python 内置的列表类型非常相似。但是随着数组在维度上变大，NumPy
数组提供了更加高效的存储和数据操作。NumPy 数组几乎是整个
Python 数据科学工具生态系统的核心。因此，不管你对数据科学的哪个
方面感兴趣，花点时间学习如何有效地使用 NumPy 都是非常值得的。</p>

<p>如果你听从前言给出的建议安装了 Anaconda，那么你已经安装好
NumPy，并可以使用它了。如果你是个体验派，则可以到 <a href='http://www.numpy.org/'>NumPy 网站</a>
（http://www.numpy.org/）按照其安装指导进行安装。安装好后，你可
以导入 NumPy 并再次核实你的 NumPy 版本：</p>

In [1]:
import numpy as np

In [3]:
numpy.__version__

'2.0.1'

<p>针对本章中介绍的 NumPy 功能，我建议你使用 NumPy 1.8 及之后的版
本。遵循传统，你将发现 SciPy / PyData 社区中的大多数人都用 np 作为
别名导入 NumPy：</p>


<p> import numpy as np </p>

当你阅读本章时，不要忘记 IPython 提供了快速探索包的内容的方
法（用 Tab 键自动补全），以及各种函数的文档（用 ? 符号）。如
果你还需要回顾一下，可以翻回 1.2 节。

例如，要显示 numpy 命名空间的所有内容，可以用如下方式：

<p> np.&lt;TAB&gt;</p>

In [5]:
np?

Type:        module
String form: <module 'numpy' from 'D:\\virtualenvs\\ai\\lib\\site-packages\\numpy\\__init__.py'>
File:        d:\virtualenvs\ai\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use

<p>要获取更详细的文档以及教程和其他资源，可以访问
<a href='http://www.numpy.org'>http://www.numpy.org。</a></p>

<h2>2.1 理解Python中的数据类型</h2>

<p>
    要实现高效的数据驱动科学和计算，需要理解数据是如何被存储和操作
的。本节将介绍在 Python 语言中数据数组是如何被处理的，并对比
NumPy 所做的改进。理解这个不同之处是理解本书其他内容的基础。<br>
Python 的用户往往被其易用性所吸引，其中一个易用之处就在于动态输
入。静态类型的语言（如 C 或 Java）往往需要每一个变量都明确地声
明，而动态类型的语言（例如 Python）可以跳过这个特殊规定。例如在
C 语言中，你可能会按照如下方式指定一个特殊的操作：
</p>

<p>注意这里最大的不同之处：在 C 语言中，每个变量的数据类型被明确地
声明；而在 Python 中，类型是动态推断的。这意味着可以将任何类型
的数据指定给任何变量：
</p>

<h3>2.1.1 Python整型不仅仅是一个整型
</h3>

<p>标准的 Python 实现是用 C 语言编写的。这意味着每一个 Python 对象都
是一个聪明的伪 C 语言结构体，该结构体不仅包含其值，还有其他信
息。例如，当我们在 Python 中定义一个整型，例如 x = 10000 时，x
并不是一个“原生”整型，而是一个指针，指向一个 C 语言的复合结构
体，结构体里包含了一些值。查看 Python 3.4 的源代码，可以发现整型
（长整型）的定义，如下所示（C 语言的宏经过扩展之后）：
</p>

<p>Python 3.4 中的一个整型实际上包括 4 个部分。</p>
<ul>
    <li>ob_refcnt 是一个引用计数，它帮助 Python 默默地处理内存的分
配和回收。</li>
    <li>ob_type 将变量的类型编码。
</li>
    <li>ob_size 指定接下来的数据成员的大小。</li>
    <li>ob_digit 包含我们希望 Python 变量表示的实际整型值。</li>
</ul>


<p>这意味着与 C 语言这样的编译语言中的整型相比，在 Python 中存储一
个整型会有一些开销，正如图 2-1 所示。</p>

<img src='../imgs/2.1.png'>

<h3>2.1.2 Python列表不仅仅是一个列表</h3>

<p>设想如果使用一个包含很多 Python 对象的 Python 数据结构，会发生什
么？ Python 中的标准可变多元素容器是列表。可以用如下方式创建一
个整型值列表：</p>

In [8]:
L = list(i for i in range(10))

In [9]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
type(L)

list

In [11]:
L2 = [str(c) for c in L]

In [12]:
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [13]:
type(L2[0])

str

In [14]:
L3 = [True,"2",3.0,4]

In [15]:
[type(item) for item in L3]

[bool, str, float, int]

<img src='../imgs/2.2.png'>

<h3>2.1.3 Python中的固定类型数组</h3>

In [1]:
import arry
L = list(range(10))
A = array.array('i',L)
A

ModuleNotFoundError: No module named 'arry'

<h3>2.1.4 从Python列表创建数组</h3>

In [2]:
import numpy as np

In [3]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

<p>请记住，不同于 Python 列表，NumPy 要求数组必须包含同一类型的数
据。如果类型不匹配，NumPy 将会向上转换（如果可行）。这里整型
被转换为浮点型：</p>

In [4]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

<p>如果希望明确设置数组的数据类型，可以用 dtype 关键字：</p>

In [5]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

<p>最后，不同于 Python 列表，NumPy 数组可以被指定为多维的。以下是
用列表的列表初始化多维数组的一种方法：</p>

In [6]:
# 嵌套列表构成的多维数组
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

<p>内层的列表被当作二维数组的行。</p>

<h3>2.1.5 从头创建数组</h3>

<p>面对大型数组的时候，用 NumPy 内置的方法从头创建数组是一种更高
效的方法。以下是几个示例：</p>

In [7]:
# 创建一个长度为10的数组，数组的值都是0
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# 创建一个3×5的浮点型数组，数组的值都是1
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# 创建一个3×5的浮点型数组，数组的值都是3.14
np.full?

Signature:
np.full(
    shape,
    fill_value,
    dtype=None,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__a

In [14]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [17]:
# 创建一个3×5的浮点型数组，数组的值是一个线性序列
# 从0开始，到20结束，步长为2
# （它和内置的range()函数类似）
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
# 创建一个5个元素的数组，这5个数均匀地分配到0~1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
# 创建一个3×3的、在0~1均匀分布的随机数组成的数组
np.random.random((3, 3))

array([[0.95815397, 0.38116369, 0.61643504],
       [0.78546274, 0.70960046, 0.32720777],
       [0.93618243, 0.79063202, 0.75523998]])

In [22]:
# 创建一个3×3的、均值为0、方差为1的
# 正态分布的随机数数组
np.random.normal(0,1,(3, 3))

array([[ 0.15457823,  1.5823835 ,  1.06070024],
       [-0.46285261,  0.83472166,  0.89872873],
       [ 0.10095818, -1.74793457, -1.19546895]])

In [23]:
np.random.normal?

Signature: np.random.normal(loc=0.0, scale=1.0, size=None)
Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

.. note::
    New code should use the `~numpy.random.Generator.normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width")

In [24]:
# 创建一个3×3的、[0, 10)区间的随机整型数组

In [25]:
np.random.randint(0,10,(3,3))

array([[5, 8, 8],
       [2, 7, 8],
       [5, 8, 7]], dtype=int32)

In [26]:
# 创建一个3×3的单位矩阵
np.eye?

Signature:
np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
# 创建一个由3个整型数组成的未初始化的数组
# 数组的值是内存空间中的任意值
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, device=None, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ens

<h3>2.1.6 NumPy标准数据类型</h3>

<p>NumPy 数组包含同一类型的值，因此详细了解这些数据类型及其限制
是非常重要的。因为 NumPy 是在 C 语言的基础上开发的，所以 C、
Fortran 和其他类似语言的用户会比较熟悉这些数据类型。</p>

<p>表 2-1 列出了标准 NumPy 数据类型。请注意，当构建一个数组时，你
可以用一个字符串参数来指定数据类型：</p>

In [39]:
arr1 = np.zeros(10,dtype='int16')

In [40]:
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

<p>或者用相关的 NumPy 对象来指定</p>


In [41]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

<h3>表2-1：NumPy标准数据类型</h3>

<table>
    <tr>
        <th>数据类型</th>
        <th>描述</th>
    </tr>
    <tr>
        <td>bool_</td>
        <td>布尔值（真、True 或假、False），用一个字节存储</td>
    </tr>
    <tr>
        <td>int_</td>
        <td>默认整型（类似于 C 语言中的 long，通常情况下是 int64 或 int32）</td>
    </tr>
    <tr>
        <td>intc</td>
        <td>同 C 语言的 int 相同（通常是 int32 或 int64）</td>
    </tr>
    <tr>
        <td>intp</td>
        <td>用作索引的整型（和 C 语言的 ssize_t 相同，通常情况下是 int32 或
int64）</td>
    </tr>
    <tr>
        <td>int8</td>
        <td>字节（byte，范围从–128 到 127）</td>
    </tr>
    <tr>
        <td>int16</td>
        <td>整型（范围从–32768 到 32767）</td>
    </tr>
    <tr>
        <td>int32</td>
        <td>整型（范围从–2147483648 到 2147483647）</td>
    </tr>
    <tr>
        <td>int64</td>
        <td>整型（范围从–9223372036854775808 到 9223372036854775807）</td>
    </tr>
    <tr>
        <td>uint8</td>
        <td>无符号整型（范围从 0 到 255）</td>
    </tr>
    <tr>
        <td>uint16</td>
        <td>无符号整型（范围从 0 到 65535）</td>
    </tr>
    <tr>
        <td>uint32</td>
        <td>无符号整型（范围从 0 到 4294967295）</td>
    </tr>
    <tr>
        <td>uint64</td>
        <td>无符号整型（范围从 0 到 18446744073709551615）</td>
    </tr>
    <tr>
        <td>float_</td>
        <td>float64 的简化形式</td>
    </tr>
    <tr>
        <td>float16</td>
        <td>半精度浮点型：符号比特位，5 比特位指数（exponent），10 比特位尾数
（mantissa）</td>
    </tr>
    <tr>
        <td>float32</td>
        <td>单精度浮点型：符号比特位，8 比特位指数，23 比特位尾数</td>
    </tr>
    <tr>
        <td>float64</td>
        <td>双精度浮点型：符号比特位，11 比特位指数，52 比特位尾数</td>
    </tr>
    <tr>
        <td>complex_</td>
        <td>complex128 的简化形式</td>
    </tr>
    <tr>
        <td>complex64</td>
        <td>复数，由两个 32 位浮点数表示</td>
    </tr>
    <tr>
        <td>complex128</td>
        <td>复数，由两个 64 位浮点数表示</td>
    </tr>
</table>

<p>还可以进行更高级的数据类型指定，例如指定高位字节数或低位字节
数；更多的信息可以在 NumPy 文档（http://numpy.org/）中查看。
NumPy 也支持复合数据类型，这一点将会在 2.9 节中介绍。</p>

<h2>2.2 NumPy数组基础</h2>

<p>Python 中的数据操作几乎等同于 NumPy 数组操作，甚至新出现的
Pandas 工具（第 3 章将介绍）也是构建在 NumPy 数组的基础之上的。
本节将展示一些用 NumPy 数组操作获取数据或子数组，对数组进行分
裂、变形和连接的例子。本节介绍的操作类型可能读起来有些枯燥，但
其中也包括了本书其他例子中将用到的内容，所以要好好了解这些内
容！
</p>

<h3>2.2.1 NumPy数组的属性</h3>

<p>
    首先介绍一些有用的数组属性。定义三个随机的数组：一个一维数组、
一个二维数组和一个三维数组。我们将用 NumPy 的随机数生成器设置
一组种子值，以确保每次程序执行时都可以生成同样的随机数组：
</p>

In [43]:
np.random.seed(0) #设置随机数种子

In [44]:
np.random.seed?

Signature:      np.random.seed(seed=None)
Call signature: np.random.seed(*args, **kwargs)
Type:           cython_function_or_method
String form:    <cyfunction seed at 0x000002B1CB16B5F0>
Docstring:     
seed(seed=None)

Reseed the singleton RandomState instance.

Notes
-----
This is a convenience, legacy function that exists to support
older code that uses the singleton RandomState. Best practice
is to use a dedicated ``Generator`` instance rather than
the random variate generation methods exposed directly in
the random module.

See Also
--------
numpy.random.Generator

In [2]:
x1 = np.random.randint(10,size=6) #创建一维数组
x2 = np.random.randint(10,size=(3,4)) #创建2维数组3行4列
x3 = np.random.randint(10,size=(3,4,5)) #创建3维数组

<p>每个数组有 nidm（数组的维度）、shape（数组每个维度的大小）和
size（数组的总大小）属性：</p>

<p>每个数组有 ndim（数组的维度 the Number of DIMision）、shape（数组每个维度的大小）和
size（数组的总大小）属性：
</p>

In [46]:
print('x3 ndim:', x3.ndim)
print('x3 shape:',x3.shape)
print('x3 size:',x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


<p>另外一个有用的属性是 dtype，它是数组的数据类型（2.1 节讨论
过）：
</p>

In [47]:
print('x3 dtype:',x3.dtype)

x3 dtype: int32


<p>其他的属性包括表示每个数组元素字节大小的 itemsize，以及表示数
组总字节大小的属性 nbytes：
</p>

In [48]:
print('itemsize:',x3.itemsize,'bytes')
print('nbytes:',x3.nbytes,'bytes')

itemsize: 4 bytes
nbytes: 240 bytes


<p>综上，我们知道nbytes等于itemsize乘size,即数组总字节的大小等于数组元素字节的大小乘上数组的总大小</p>

<p>一般来说，可以认为 nbytes 跟 itemsize 和 size 的乘积大小相等</p>

<h3>2.2.2 数组索引：获取单个元素</h3>

<p>如果你熟悉 Python 的标准列表索引，那么你对 NumPy 的索引方式也不
会陌生。和 Python 列表一样，在一维数组中，你也可以通过中括号指
定索引获取第 i 个值（从 0 开始计数）：</p>

In [49]:
x1

array([5, 0, 3, 3, 7, 9], dtype=int32)

In [50]:
x1[0]

np.int32(5)

In [51]:
x1[4]

np.int32(7)

<p>为了获取数组的末尾索引，可以用负值索引：</p>

In [52]:
x1[-1]

np.int32(9)

In [53]:
x1[-2]

np.int32(7)

<p>在多维数组中，可以用逗号分隔的索引元组获取元素：</p>

In [54]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]], dtype=int32)

In [55]:
x2[0,0] #第0行第0列

np.int32(3)

In [56]:
x2[2,0] #第2行第0列

np.int32(1)

In [57]:
x2[2,-1] #第2行倒数第一列

np.int32(7)

<p>也可以用以上索引方式修改元素值：</p>

In [3]:
x2[0,0] = 12
x2

array([[12,  8,  4,  4],
       [ 4,  0,  8,  2],
       [ 7,  1,  5,  7]], dtype=int32)

<p>请注意，和 Python 列表不同，NumPy 数组是固定类型的。这意味着当
你试图将一个浮点值插入一个整型数组时，浮点值会被截短成整型。并
且这种截短是自动完成的，不会给你提示或警告，所以需要特别注意这
一点！
</p>

In [59]:
x1[0] = 3.14159 #这将被截短
x1

array([3, 0, 3, 3, 7, 9], dtype=int32)

<h3>2.2.3 数组切片：获取子数组</h3>

<p>正如此前用中括号获取单个数组元素，我们也可以用切片（slice）符号
获取子数组，切片符号用冒号（:）表示。NumPy 切片语法和 Python 列
表的标准切片语法相同。为了获取数组 x 的一个切片，可以用以下方
式：
</p>

In [ ]:
x1[start:stop:step]

<p>如果以上 3 个参数都未指定，那么它们会被分别设置默认值 start=0、
stop= 维度的大小（size of dimension）和 step=1。我们将详细介
绍如何在一维和多维数组中获取子数组。</p>

<h4>01. 一维子数组</h4>

In [6]:
x=np.arange(10)

In [7]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x[:5] #获取前五个元素

array([0, 1, 2, 3, 4])

In [9]:
x[5:] #获取从第五个元素开始到最后一个元素结束

array([5, 6, 7, 8, 9])

In [10]:
x[4:7] #取到中间的子数组

array([4, 5, 6])

In [13]:
x[::2] #以步长为2取到x数组中的元素

array([0, 2, 4, 6, 8])

In [14]:
x[1::2] #从下标索引为1的数组元素开始取步长为2

array([1, 3, 5, 7, 9])

<p>你可能会在步长值为负时感到困惑。在这个例子中，start 参数和
stop 参数默认是被交换的。如果有疑问说明python的各种含有下标元素索引的地方你都没学好</p>

<p>因此这是一种非常方便的逆序数组的方式：</p>

In [15]:
x[::-1] #从最后一个元素往前取即逆序取出数组所有元素

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [18]:
x[5::-2] #逆序取数组元素步长为2，从索引5开始

array([5, 3, 1])

<img src='../imgs/数组逆序取值.png'>

<h4>02. 多维子数组</h4>

<p>多维切片也采用同样的方式处理，用冒号分隔。例如：</p>

In [19]:
x2

array([[12,  8,  4,  4],
       [ 4,  0,  8,  2],
       [ 7,  1,  5,  7]], dtype=int32)

In [20]:
x2[:2,:3] #第一个是取行,即从索引下标为0行开始取取到第索引下标第2行(不包含第二行结束)，:3依此类推

array([[12,  8,  4],
       [ 4,  0,  8]], dtype=int32)

<img src='../imgs/hint.png'>

In [22]:
x2[:3,::2] #取到索引下标为3前的所有行列全取,但是步长都为2

array([[12,  4],
       [ 4,  8],
       [ 7,  5]], dtype=int32)

<p>最后，子数组维度也可以同时被逆序</p>

In [23]:
x2[::-1,::-1]

array([[ 7,  5,  1,  7],
       [ 2,  8,  0,  4],
       [ 4,  4,  8, 12]], dtype=int32)

<h5>03. 获取数组的行和列</h5>

<p>一种常见的需求是获取数组的单行和单列。你可以将索引与切片组
合起来实现这个功能，用一个冒号（:）表示空切片：
</p>

In [24]:
print(x2[:,0]) #x2的第一列

[12  4  7]


In [25]:
print(x2[0,:]) #x2的第一行

[12  8  4  4]


<p>在获取行时，出于语法的简介考虑，可以省略空的切片：</p>

In [26]:
print(x2[0]) #相当于x2[0,:]

[12  8  4  4]


<h4>04. 非副本视图的子数组</h4>

<p>关于数组切片有一点很重要也非常有用，那就是数组切片返回的是
数组数据的视图，而不是数值数据的副本。这一点也是 NumPy 数
组切片和 Python 列表切片的不同之处：在 Python 列表中，切片是
值的副本。例如此前示例中的那个二维数组：
</p>

In [27]:
print(x2)

[[12  8  4  4]
 [ 4  0  8  2]
 [ 7  1  5  7]]


<p>从中抽取一个 2×2 的子数组</p>

In [28]:
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  8]
 [ 4  0]]


<p>现在如果修改这个子数组，将会看到原始数组也被修改了！结果如
下所示：</p>

In [29]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  8]
 [ 4  0]]


In [30]:
print(x2)

[[99  8  4  4]
 [ 4  0  8  2]
 [ 7  1  5  7]]


<p>这种默认的处理方式实际上非常有用：它意味着在处理非常大的数
据集时，可以获取或处理这些数据集的片段，而不用复制底层的数
据缓存</p>

<h4>05. 创建数组的副本</h4>

<P>尽管数组视图有一些非常好的特性，但是在有些时候明确地复制数
组里的数据或子数组也是非常有用的。可以很简单地通过 copy()
方法实现：</P>

In [34]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  8]
 [ 4  0]]


<p>如果修改这个子数组，原始的数组不会被改变：</p>

In [35]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  8]
 [ 4  0]]


In [37]:
print(x2)

[[99  8  4  4]
 [ 4  0  8  2]
 [ 7  1  5  7]]


In [39]:
# 简单理解如果只是单纯的写了一个变量来接收数组那么就会默认对原数组进行修改
# 但是如果用了.copy(),那么就会创建一个副本，修改这个副本不会影响原来的数组
# 如果仍有疑惑需要返回去查看python的浅拷贝和深拷贝

<h3>2.2.4 数组的变形</h3>

<p>另一个有用的操作类型是数组的变形。数组变形最灵活的实现方式是通
过 reshape() 函数来实现。例如，如果你希望将数字 1~9 放入一个
3×3 的矩阵中，可以采用如下方法：</p>

In [40]:
grid = np.arange(1,10).reshape((3,3)) #左闭右开所以取到的就是1-9共9个数,数字10是不被包含在内的
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<p>请注意，如果希望该方法可行，那么原始数组的大小必须和变形后数组
的大小一致。如果满足这个条件，reshape 方法将会用到原始数组的一
个非副本视图。但实际情况是，在非连续的数据缓存的情况下，返回非
副本视图往往不可能实现。</p>

<p>另外一个常见的变形模式是将一个一维数组转变为二维的行或列的矩
阵。你也可以通过 reshape 方法来实现，或者更简单地在一个切片操
作中利用 newaxis 关键字：</p>

In [57]:
x=np.array([1,2,3]) #单纯的一维数组

In [59]:
x.ndim #我们可以利用.ndim查看数组的维度可以看到它是一个一维数组

1

In [60]:
#通过变形获得的行向量
x.reshape((1,3))

array([[1, 2, 3]])

In [62]:
x.ndim #现在是一个一行三列的一维数组,接下来我们将进行一些操作将其改变

1

In [64]:
# 通过newaxis获得的行向量
x[np.newaxis,:]

array([[1, 2, 3]])

In [66]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [67]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

<h3>2.2.5 数组拼接和分裂</h3>

<p>以上所有的操作都是针对单一数组的，但有时也需要将多个数组合并为
一个，或将一个数组分裂成多个。接下来将详细介绍这些操作。
</p>

<h4>01. 数组的拼接</h4>

<P>拼接或连接 NumPy 中的两个数组主要由
np.concatenate、np.vstack 和 np.hstack 例程实
现。np.concatenate 将数组元组或数组列表作为第一个参数，如
下所示：</P>

In [69]:
x=np.array([1,2,3])
y=np.array([3,2,1])
# 先看看怎么用
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

In [ ]:
# 可以从提示信息中看到其中的参数有哪些,其中默认axies为0，即默认按照第一个轴(横轴)拼接

In [70]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

<p>你也可以一次性拼接两个以上数组：</p>

In [71]:
 z = [99, 99, 99]

In [72]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

<p>np.concatenate 也可以用于二维数组的拼接：</p>

In [73]:
grid=np.array([[1,2,3],[4,5,6]])

In [75]:
# 沿着第1个轴拼接

In [76]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [77]:
 # 沿着第二个轴拼接（从0开始索引）
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

<p>沿着固定维度处理数组时，使用 np.vstack（垂直栈）和
np.hstack（水平栈）函数会更简洁：</p>

In [80]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])

In [81]:
grid

array([[9, 8, 7],
       [6, 5, 4]])

In [82]:
grid.shape

(2, 3)

In [83]:
#垂直栈数组 virticla stack
np.vstack([x,grid]) 

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [84]:
#水平栈数组 horizental stack
y=np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [85]:
# 学习以上记得vstack是拼接为新的一行,第一个维度
# 而hstack是拼接新的一列,第二个维度

In [ ]:
# 与之类似,np.dstack将沿着第三个维度拼接数组。

<h4>02. 数组的分裂
</h4>

<p>与拼接相反的过程是分裂。分裂可以通过 np.split、np.hsplit
和 np.vsplit 函数来实现。可以向以上函数传递一个索引列表作
为参数，索引列表记录的是分裂点位置：</p>

In [86]:
x = [1, 2, 3, 99, 99, 3, 2, 1]

In [87]:
x1,x2,x3 = np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


<p>值得注意的是，N 分裂点会得到 N + 1 个子数组。相关的
np.hsplit 和 np.vsplit 的用法也类似</p>

In [88]:
grid = np.arange(16).reshape((4,4))

In [89]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
upper,lower = np.vsplit(grid,[2]) #按行切分成两份,前面得有俩变量进行接收
print(upper) 
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [91]:
left,right = np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


<p>同样，np.dsplit 将数组沿着第三个维度分裂。</p>

<h2>2.3 NumPy数组的计算：通用函数</h2>

<p>到目前为止，我们讨论了 NumPy 的一些基础知识。在接下来的几小节
中，我们将深入了解 NumPy 在 Python 数据科学世界中如此重要的原
因。明确点说，NumPy 提供了一个简单灵活的接口来优化数据数组的
计算。
NumPy 数组的计算有时非常快，有时也非常慢。使 NumPy 变快的关键
是利用向量化操作，通常在 NumPy 的通用函数（ufunc）中实现。本节
将介绍 NumPy 通用函数的重要性——它可以提高数组元素的重复计算
的效率；然后，将会介绍很多 NumPy 包中常用且有用的数学通用函
数。
<p>

<h3>2.3.1 缓慢的循环</h3>

<p>Python 的默认实现（被称作 CPython）处理起某些操作时非常慢，一部
分原因是该语言的动态性和解释性——数据类型灵活的特性决定了序列
操作不能像 C 语言和 Fortran 语言一样被编译成有效的机器码。目前，
有一些项目试图解决 Python 这一弱点，比较知名的包括：PyPy 项目
（http://pypy.org/），一个实时的 Python 编译实现；Cython 项目
（http://cython.org），将 Python 代码转换成可编译的 C 代码；Numba
项目（http://numba.pydata.org/），将 Python 代码的片段转换成快速的
LLVM 字节码。以上这些项目都各有其优势和劣势，但是比较保守地
说，这些方法中还没有一种能达到或超过标准 CPython 引擎的受欢迎程
度。
</p>

<p>Python 的相对缓慢通常出现在很多小操作需要不断重复的时候，比如对
数组的每个元素做循环操作时。假设有一个数组，我们想计算每个元素
的倒数，一种直接的解决方法是：</p>

In [95]:
import numpy as np
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output
values = np.random.randint(1,10,size=5)
compute_reciprocals(values)

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

<p>这种实现方式可能对于有 C 语言或 Java 背景的人来说非常自然，但是
如果测试一个很大量的输入数据运行上述代码的时间，这一操作将非常
耗时，并且是超出意料的慢！我们将用 IPython 的 %timeit 魔法函数
（详情请参见 1.9 节）来测量：</p>

In [96]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.82 s ± 43.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


<p>完成百万次上述操作并存储结果花了几秒钟的时间！在手机都以 GigaFLOPS（即每秒十亿次浮点运算）为单位计算处理速度时，上面的处理
结果所花费的时间确实是不合时宜的慢。事实上，这里的处理瓶颈并不
是运算本身，而是 CPython 在每次循环时必须做数据类型的检查和函数
的调度。每次进行倒数运算时，Python 首先检查对象的类型，并且动态
查找可以使用该数据类型的正确函数。如果我们在编译代码时进行这样
的操作，那么就能在代码执行之前知晓类型的声明，结果的计算也会更
加有效率</p>

<h3>2.3.2 通用函数介绍</h3>

<p>NumPy 为很多类型的操作提供了非常方便的、静态类型的、可编译程
序的接口，也被称作向量操作。你可以通过简单地对数组执行操作来实
现，这里对数组的操作将会被用于数组中的每一个元素。这种向量方法
被用于将循环推送至 NumPy 之下的编译层，这样会取得更快的执行效
率。</p>

<p>比较以下两个结果：</p>

In [97]:
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


<p>如果计算一个较大数组的运行时间，可以看到它的完成时间比 Python
循环花费的时间更短：</p>

In [99]:
%timeit (1.0/big_array)

3.07 ms ± 36.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


<p>NumPy 中的向量操作是通过通用函数实现的。通用函数的主要目的是
对 NumPy 数组中的值执行更快的重复操作。它非常灵活，前面我们看
过了标量和数组的运算，但是也可以对两个数组进行运算：</p>

In [100]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

<p>通用函数并不仅限于一维数组的运算，它们也可以进行多维数组的运
算：</p>

In [101]:
x=np.arange(9).reshape((3,3))

In [102]:
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

<p>通过通用函数用向量的方式进行计算几乎总比用 Python 循环实现的计
算更加有效，尤其是当数组很大时。只要你看到 Python 脚本中有这样
的循环，就应该考虑能否用向量方式替换这个循环。</p>

<h3>2.3.3 探索NumPy的通用函数</h3>

<p>通用函数有两种存在形式：一元通用函数（unary ufunc）对单个输入操
作，二元通用函数（binary ufunc）对两个输入操作。我们将在以下的介
绍中看到这两种类型的例子。</p>

<h4>01. 数组的运算</h4>

<p>NumPy 通用函数的使用方式非常自然，因为它用到了 Python 原生
的算术运算符，标准的加、减、乘、除都可以使用：</p>

In [103]:
x=np.arange(4)
print(f'x={x}')
print(f'x+5={x+5}')
print(f'x-5={x-5}')
print(f'x*2={x*2}')
print(f'x/2={x/2}')
print(f'x//2={x//2}') #地板除运算符

x=[0 1 2 3]
x+5=[5 6 7 8]
x-5=[-5 -4 -3 -2]
x*2=[0 2 4 6]
x/2=[0.  0.5 1.  1.5]
x//2=[0 0 1 1]


<p>还有逻辑非、** 表示的指数运算符和 % 表示的模运算符的一元通
用函数：</p>

In [104]:
print(f'-x={-x}')
print(f'x**2={x**2}')
print(f'x%2={x%2}')

-x=[ 0 -1 -2 -3]
x**2=[0 1 4 9]
x%2=[0 1 0 1]


<p>你可以任意将这些算术运算符组合使用。当然，你得考虑这些运算
符的优先级：
</p>

In [105]:
-(0.5*x+1)**2

array([-1.  , -2.25, -4.  , -6.25])

<p>所有这些算术运算符都是 NumPy 内置函数的简单封装器，例如 +
运算符就是一个 add 函数的封装器：</p>

In [106]:
np.add(x,2)

array([2, 3, 4, 5])

<p>表 2-2 列出了所有 NumPy 实现的算术运算符。</p>

<table>
    <tr>
        <th>运算符</th>
        <th>对应的通用函数</th>
        <th>描述</th>
    </tr>
    <tr>
        <td>+</td>
        <td>np.add</td>
        <td>加法运算</td>
    </tr>
    <tr>
        <td>-</td>
        <td>np.subtract</td>
        <td>减法运算</td>
    </tr>
    <tr>
        <td>-</td>
        <td>np.negative</td>
        <td>负数运算</td>
    </tr>
    <tr>
        <td>*</td>
        <td>np.multiply</td>
        <td>乘法运算</td>
    </tr>
    <tr>
        <td>/</td>
        <td>np.divide</td>
        <td>除法运算</td>
    </tr>
    <tr>
        <td>//</td>
        <td>np.floor_divide</td>
        <td>地板除法运算</td>
    </tr>
    <tr>
        <td>**</td>
        <td>np.power</td>
        <td>指数运算</td>
    </tr>
    <tr>
        <td>&</td>
        <td>np.mod</td>
        <td>模/余数</td>
    </tr>
</table>

<p>另外，NumPy 中还有布尔 / 位运算符，这些运算符将在 2.6 节中进
一步介绍。</p>

<h4>02. 绝对值</h4>

<p>正如 NumPy 能理解 Python 内置的运算操作，NumPy 也可以理解
Python 内置的绝对值函数：</p>

In [107]:
x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

<p>对应的 NumPy 通用函数是 np.absolute，该函数也可以用别名
np.abs 来访问：</p>

In [108]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [109]:
np.abs(x)

array([2, 1, 0, 1, 2])

<p>这个通用函数也可以处理复数。当处理复数时，绝对值返回的是该
复数的幅度：</p>

In [110]:
x=np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

<h4>03. 三角函数</h4>

<p>NumPy 提供了大量好用的通用函数，其中对于数据科学家最有用
的就是三角函数。首先定义一个角度数组：</p>

In [111]:
theta = np.linspace(0,np.pi,3)

<p>现在可以对这些值进行一些三角函数计算：
</p>

In [112]:
print(f'thta:{theta}')
print(f'sin(thta):{np.sin(theta)}')
print(f'cos(thta):{np.cos(theta)}')
print(f'tan(thta):{np.tan(theta)}')


thta:[0.         1.57079633 3.14159265]
sin(thta):[0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(thta):[ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(thta):[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


<p>这些值是在机器精度内计算的，所以有些应该是 0 的值并没有精确
到 0 。逆三角函数同样可以使用：</p>

In [114]:
x=[-1,0,1]
print(f'x={x}')
print(f'arcsin(x)={np.arcsin(x)}')
print(f'arccos(x)={np.arccos(x)}')
print(f'arctan(x)={np.arctan(x)}')


x=[-1, 0, 1]
arcsin(x)=[-1.57079633  0.          1.57079633]
arccos(x)=[3.14159265 1.57079633 0.        ]
arctan(x)=[-0.78539816  0.          0.78539816]


<h4>04. 指数和对数</h4>

<p>NumPy 中另一个常用的运算通用函数是指数运算：</p>

In [ ]:
# p108